<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CoursesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        {
            DB::table('courses')->insert([
            [
                'code' => '00001',
                'name_en' => 'SecDevOps Foundation® (SDOF) Certification Training',
                'name_fr' => 'Formation certifiante SecDevOps Foundation® (SDOF)',
                'description_en' => 'This SecDevOps Foundation® (SDOF) Certification Training course will help you prepare for and successfully attain the SecDevOps Foundation Certification.',
                'description_fr' => "Ce cours de formation à la certification SecDevOps Foundation® (SDOF) vous aidera à préparer et à obtenir avec succès la certification SecDevOps Foundation.",
                'url_tag' => 'secdevops-foundation-sdof-certification-training',
                'level_en' => 'Intermediate',
                'level_fr' => 'Intermédiaire',
                'duration_en' => '16 hours',
                'duration_fr' => '16 heures',
                'duration_type' => 'hour',
                'duration_number' => 16,
                'after_course' => true,
                'learning_mode_en' => 'Online or In-Class',
                'learning_mode_fr' => 'En ligne ou en Présentiel',
                'price_euro' => 3000.00,
                'price_fcfa' => 1974344.00,
                'status_en' => 'new',
                'status_fr' => 'nouveau',
                'published' => true,
                'instructor_id' => 1,
                'category_id' => 52,
                'certification_id' => 1,
                'vendor_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],

            [
                'code' => '00002',
                'name_en' => 'Microsoft Power Platform Fundamentals Training (PL-900)',
                'name_fr' => 'Formation sur les principes fondamentaux de Microsoft Power Platform (PL-900)',
                'description_en' => 'In this Microsoft Power Platform training, learn the business value and product capabilities of Microsoft Power Platform. Create simple Power Apps, connect data with Dataverse, build a Power BI (Business Intelligence) Dashboard, and automate processes with Power Automate.',
                'description_fr' => "Dans cette formation Microsoft Power Platform, découvrez la valeur commerciale et les capacités du produit Microsoft Power Platform. Créez des Power Apps simples, connectez les données avec Dataverse, créez un tableau de bord Power BI (Business Intelligence) et automatisez les processus avec Power Automate.",
                'url_tag' => 'microsoft-power-platform-fundamentals-training-pl-900',
                'level_en' => 'Intermediate',
                'level_fr' => 'Intermédiaire',
                'duration_en' => '48 hours',
                'duration_fr' => '48 heures',
                'duration_type' => 'hour',
                'duration_number' => 48,
                'after_course' => true,
                'learning_mode_en' => 'Online or In-Class',
                'learning_mode_fr' => 'En ligne ou en Présentiel',
                'price_euro' => 2800.00,
                'price_fcfa' => 1838583.26,
                'status_en' => 'new',
                'status_fr' => 'nouveau',
                'published' => true,
                'instructor_id' => 1,
                'category_id' => 44,
                'certification_id' => 1,
                'vendor_id' => 18,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'code' => '00003',
                'name_en' => '21ST Century Leadership: Inspiring Excellence And Engagement',
                'name_fr' => 'Leadership du 21e siècle : inspirer l’excellence et l’engagement',
                'description_en' => 'The challenges of a contemporary workplace present unique growth opportunities for leaders in the 21st century. In this training course, you learn to manage the sea change revolutionizing business today, consider the impact of swift and evolving technologies, and understand the needs of a culturally diverse and multi-generational workforce in an uncertain business environment',
                'description_fr' => "Les défis du monde du travail contemporain présentent des opportunités de croissance uniques pour les dirigeants du 21e siècle. Dans cette formation, vous apprendrez à gérer les changements radicaux qui révolutionnent les entreprises aujourd'hui, à considérer l'impact des technologies rapides et évolutives et à comprendre les besoins d'une main-d'œuvre culturellement diversifiée et multigénérationnelle dans un environnement commercial incertain.",
                'url_tag' => '21st-century-leadership-inspiring-excellence-and-engagemen',
                'level_en' => 'Intermediate',
                'level_fr' => 'Intermédiaire',
                'duration_en' => '10 hours',
                'duration_fr' => '10 heures',
                'duration_type' => 'hour',
                'duration_number' => 10,
                'after_course' => true,
                'learning_mode_en' => 'Online or In-Class',
                'learning_mode_fr' => 'En ligne ou en Présentiel',
                'price_euro' => 1500.00,
                'price_fcfa' => 980875.88,
                'status_en' => 'new',
                'status_fr' => 'nouveau',
                'published' => true,
                'instructor_id' => 1,
                'category_id' => 52,
                'certification_id' => 1,
                'vendor_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'code' => '00004',
                'name_en' => 'It Project Management',
                'name_fr' => 'Gestion de projet informatique',
                'description_en' => 'Learn the fundamentals and best practices of project management methodology as applied to IT initiatives, and practice and master the skills you need to deliver IT projects on time, within budget, and to specification. Examine all aspects of IT projects, including hardware, software, vendor relationships, communicating with different audiences, and working with virtual teams. Learn to determine project scope through effective requirements identification, set and manage stakeholder expectations, identify and manage IT risks, and meet quality standards. Learn how to overcome the most common pitfalls of IT project success.
                                    Students pursuing a university-recognized and/or accredited certificate in Canada or continuing education units in the US must attend at least 90% of class time, participate in class exercises and section-knowledge checks, and score at least 70% on an end-of-class, multiple-choice assessment.',
                'description_fr' => "Apprenez les principes fondamentaux et les meilleures pratiques de la méthodologie de gestion de projet appliquée aux initiatives informatiques, et mettez en pratique et maîtrisez les compétences dont vous avez besoin pour livrer des projets informatiques dans les délais, dans les limites du budget et des spécifications. Examinez tous les aspects des projets informatiques, y compris le matériel, les logiciels, les relations avec les fournisseurs, la communication avec différents publics et le travail avec des équipes virtuelles. Apprenez à déterminer la portée du projet grâce à une identification efficace des exigences, à définir et à gérer les attentes des parties prenantes, à identifier et à gérer les risques informatiques et à respecter les normes de qualité. Apprenez à surmonter les pièges les plus courants liés à la réussite d'un projet informatique.
                                    Les étudiants qui poursuivent un certificat reconnu et/ou accrédité par une université au Canada ou des unités de formation continue aux États-Unis doivent assister à au moins 90 % du temps de cours, participer aux exercices en classe et aux contrôles de connaissances des sections, et obtenir au moins 70 % à la fin. évaluation à choix multiples en classe.",
                'url_tag' => 'it-project-management',
                'level_en' => 'Intermediate',
                'level_fr' => 'Intermédiaire',
                'duration_en' => '15 hours',
                'duration_fr' => '15 heures',
                'duration_type' => 'hour',
                'duration_number' => 15,
                'after_course' => true,
                'learning_mode_en' => 'Online',
                'learning_mode_fr' => 'En ligne',
                'price_euro' => 2500.00,
                'price_fcfa' => 1640429.43,
                'status_en' => 'new',
                'status_fr' => 'nouveau',
                'published' => true,
                'instructor_id' => 2,
                'category_id' => 54,
                'certification_id' => 8,
                'vendor_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'code' => '00005',
                'name_en' => 'Certified Information Systems Auditor (CISA) Training',
                'name_fr' => "Formation d'auditeur certifié des systèmes d'information (CISA)",
                'description_en' => 'An ISACA CISA (Certified Information Systems Auditor) is recognized as one of the leading authorities in the areas of IS (Information Systems) auditing, control, and information security. This official CISA training course provides in-depth coverage of the five CISA domains covered on the CISA certification exam. These domains include auditing information systems; IT (Information Technology) governance and management of IT; information systems acquisition, development, and implementation; information systems operations, maintenance, and support; and protection of information assets.
                                     In addition to meeting ISACA’s certification requirements, passing the CISA Certification Exam meets U.S. DoD Directive 8140/8570.01 Technical (IAT) Level-III and CSSP Auditor requirements.',
                'description_fr' => "Un ISACA CISA (Certified Information Systems Auditor) est reconnu comme l'une des principales autorités dans les domaines de l'audit, du contrôle et de la sécurité de l'information des SI (Systèmes d'Information). Ce cours de formation officiel CISA offre une couverture approfondie des cinq domaines CISA couverts lors de l'examen de certification CISA. Ces domaines comprennent l'audit des systèmes d'information ; Gouvernance informatique (technologies de l'information) et gestion de l'informatique ; acquisition, développement et mise en œuvre de systèmes d'information ; opérations, maintenance et support des systèmes d’information ; et la protection des actifs informationnels.
                                    En plus de répondre aux exigences de certification de l'ISACA, la réussite de l'examen de certification CISA répond aux exigences de la directive technique (IAT) niveau III du DoD des États-Unis 8140/8570.01 et des exigences de l'auditeur CSSP.",
                'url_tag' => 'certified-information-systems-auditor-training',
                'level_en' => 'Intermediate',
                'level_fr' => 'Intermédiaire',
                'duration_en' => '4 days',
                'duration_fr' => '4 jours',
                'duration_type' => 'day',
                'duration_number' => 4,
                'after_course' => true,
                'learning_mode_en' => 'Online or In-Class',
                'learning_mode_fr' => 'En ligne ou en Présentiel',
                'price_euro' => 2441.00,
                'price_fcfa' => 1600000,
                'status_en' => 'new',
                'status_fr' => 'nouveau',
                'published' => true,
                'instructor_id' => 2,
                'category_id' => 54,
                'certification_id' => 10,
                'vendor_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],

            ]);


        }
    }
}
