<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class LessonsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('lessons')->insert([

            [
                'module_id' => 1,
                'title_en' => 'What is Agile/DevOps?',
                'title_fr' => 'Qu’est-ce qu’Agile/DevOps ?',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 1,
                'title_en' => 'DevOps Goals',
                'title_fr' => 'Objectifs DevOps',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 1,
                'title_en' => 'DevOps Values',
                'title_fr' => 'Valeurs DevOps',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 1,
                'title_en' => 'DevOps Stakeholders',
                'title_fr' => 'Parties prenantes du DevOps',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 2,
                'title_en' => 'Key terms and concepts',
                'title_fr' => 'Termes et concepts clés',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 2,
                'title_en' => 'Why SecDevOps is important',
                'title_fr' => 'Pourquoi SecDevOps est important',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 2,
                'title_en' => '3 Ways to think about DevOps + Security',
                'title_fr' => '3 façons de penser DevOps + Sécurité',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 2,
                'title_en' => 'Key principles of SecDevOps',
                'title_fr' => 'Principes clés du SecDevOps',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 2,
                'title_en' => 'SecDevOps security-first philosophy',
                'title_fr' => 'Philosophie SecDevOps axée sur la sécurité',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 2,
                'title_en' => 'SecDevOps evolution from DevSecOps',
                'title_fr' => 'Évolution de SecDevOps à partir de DevSecOps',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 3,
                'title_en' => 'Key terms and concepts',
                'title_fr' => 'Termes et concepts clés',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 3,
                'title_en' => 'How much security is enough?',
                'title_fr' => 'Dans quelle mesure la sécurité est-elle suffisante ?',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 3,
                'title_en' => 'Threat modeling',
                'title_fr' => 'Modélisation des menaces',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 3,
                'title_en' => 'Context is everything',
                'title_fr' => 'Le contexte est tout',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 3,
                'title_en' => 'High-velocity risk management',
                'title_fr' => 'Gestion des risques à haute vitesse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 3,
                'title_en' => 'Team security profiling',
                'title_fr' => "Profilage de sécurité de l'équipe",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 4,
                'title_en' => 'Avoiding the checkbox trap',
                'title_fr' => "Éviter le piège des cases à cocher",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 4,
                'title_en' => 'Basic security hygiene',
                'title_fr' => "Hygiène de sécurité de base",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 4,
                'title_en' => 'Architectural considerations',
                'title_fr' => "Considérations architecturales",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 4,
                'title_en' => 'Federated identity',
                'title_fr' => "Identité fédérée",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 4,
                'title_en' => 'Log management',
                'title_fr' => "Gestion des journaux",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 5,
                'title_en' => 'Configuration management',
                'title_fr' => "Gestion des journaux",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 5,
                'title_en' => 'Centralized workflow',
                'title_fr' => "Flux de travail centralisé",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 5,
                'title_en' => 'Workflow branch classifications',
                'title_fr' => "Classifications des branches de workflow",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 5,
                'title_en' => 'Pre- and post-commit',
                'title_fr' => "Pré et post-commit",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 5,
                'title_en' => 'Deployment and release orchestration',
                'title_fr' => "Orchestration du déploiement et des versions",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 6,
                'title_en' => 'Needs Phase requirements vs. security',
                'title_fr' => "Besoins Exigences de la phase par rapport à la sécurité",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 6,
                'title_en' => 'Acquisition Review Board (ARB)',
                'title_fr' => "Commission d'examen des acquisitions (ARB)",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 6,
                'title_en' => 'Analyze/Select Phase measurement metrics',
                'title_fr' => "Analyser/Sélectionner les métriques de mesure de phase",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 6,
                'title_en' => 'Obtain phase life cycle',
                'title_fr' => "Obtenir le cycle de vie des phases",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 6,
                'title_en' => 'Planning and scheduling',
                'title_fr' => "Planification et ordonnancement",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 6,
                'title_en' => 'Dispose phase concerns',
                'title_fr' => "Éliminer les problèmes de phase",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 7,
                'title_en' => 'Key terms and concepts',
                'title_fr' => "Termes et concepts clés",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 7,
                'title_en' => 'Identity and Access Management (IAM) basic concepts',
                'title_fr' => "Concepts de base de la gestion des identités et des accès (IAM)",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 7,
                'title_en' => 'Why IAM is important',
                'title_fr' => "Pourquoi l'IAM est important",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 7,
                'title_en' => 'Implementation guidance',
                'title_fr' => "Conseils de mise en œuvre",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 7,
                'title_en' => 'Automation opportunities',
                'title_fr' => "Opportunités d'automatisation",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 7,
                'title_en' => 'How to hurt yourself with IAM',
                'title_fr' => "Comment se blesser avec IAM",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 8,
                'title_en' => 'Application Security Testing (AST)',
                'title_fr' => "Tests de sécurité des applications (AST)",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 8,
                'title_en' => 'Testing Techniques',
                'title_fr' => "Techniques de test",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 8,
                'title_en' => 'Prioritizing Testing Techniques',
                'title_fr' => "Prioriser les techniques de test",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 8,
                'title_en' => 'Issue Management Integration',
                'title_fr' => "Intégration de la gestion des problèmes",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 8,
                'title_en' => 'Threat Monitoring',
                'title_fr' => "Surveillance des menaces",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 8,
                'title_en' => 'Leveraging Automation',
                'title_fr' => "Tirer parti de l'automatisation",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 8,
                'title_en' => 'Secure coding and Open Web Application Security Project (OWASP) compliance',
                'title_fr' => "Codage sécurisé et conformité au Open Web Application Security Project (OWASP)",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 9,
                'title_en' => 'Key terms and concepts',
                'title_fr' => "Termes et concepts clés",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 9,
                'title_en' => 'Basic security hygiene practices',
                'title_fr' => "Pratiques d’hygiène de sécurité de base",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 9,
                'title_en' => 'Role of operations management',
                'title_fr' => "Rôle de la gestion des opérations",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 9,
                'title_en' => 'The Ops environment',
                'title_fr' => "L’environnement opérationnel",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 9,
                'title_en' => 'Embracing fail-early, fail-first',
                'title_fr' => "Adopter l’échec précoce, l’échec d’abord",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 9,
                'title_en' => 'Security infrastructure as code',
                'title_fr' => "Infrastructure de sécurité sous forme de code",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 10,
                'title_en' => 'Key terms and concepts',
                'title_fr' => "Termes et concepts clés",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 10,
                'title_en' => 'Establishing trust',
                'title_fr' => "Établir la confiance",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 10,
                'title_en' => 'Promoting shared responsibility',
                'title_fr' => "Promouvoir la responsabilité partagée",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 10,
                'title_en' => 'Team verification techniques',
                'title_fr' => "Techniques de vérification d'équipe",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 10,
                'title_en' => 'Embedded point-of-contact',
                'title_fr' => "Point de contact intégré",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 10,
                'title_en' => 'Security, development, and operations sprints',
                'title_fr' => "Sprints de sécurité, de développement et d’opérations",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 11,
                'title_en' => 'SecDevOps Coach',
                'title_fr' => "Coach SecDevOps",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 11,
                'title_en' => 'Product Owner Expanded Responsibilities',
                'title_fr' => "Responsabilités élargies du Product Owner",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 11,
                'title_en' => 'Program and Project Manager',
                'title_fr' => "Gestionnaire de programme et de projet",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 11,
                'title_en' => 'Information System Security Officer (ISSO)',
                'title_fr' => "Responsable de la Sécurité des Systèmes d'Information (ISSO)",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 11,
                'title_en' => 'SecDevOps Engineer',
                'title_fr' => "Ingénieur SecDevOps",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 11,
                'title_en' => 'Site Reliability Engineer',
                'title_fr' => "Ingénieur Fiabilité des Sites",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 12,
                'title_en' => 'Key terms and concepts',
                'title_fr' => "Termes et concepts clés",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 12,
                'title_en' => 'What is GRC?',
                'title_fr' => "Qu’est-ce que le GRC ?",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 12,
                'title_en' => 'Why care about GRC?',
                'title_fr' => "Pourquoi se soucier du GRC ?",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 12,
                'title_en' => 'Rethinking policies',
                'title_fr' => "Repenser les politiques",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 12,
                'title_en' => 'Policy as code',
                'title_fr' => "Politique en tant que code",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 12,
                'title_en' => 'Shifting audit left',
                'title_fr' => "Déplacement de l'audit vers la gauche",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 12,
                'title_en' => 'Three myths of segregation of duties vs. DevOps',
                'title_fr' => "Trois mythes sur la séparation des tâches par rapport au DevOps",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 13,
                'title_en' => 'Key terms and concepts',
                'title_fr' => "Termes et concepts clés",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 13,
                'title_en' => 'Setting up log management',
                'title_fr' => "Configuration de la gestion des journaux",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 13,
                'title_en' => 'Incident response and forensics',
                'title_fr' => "Réponse aux incidents et criminalistique",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 13,
                'title_en' => 'Threat intelligence and information sharing',
                'title_fr' => "Intelligence sur les menaces et partage d’informations",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 14,
                'title_en' => 'Exam review',
                'title_fr' => "Révision de l'examen",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 14,
                'title_en' => 'Key course concepts',
                'title_fr' => "Concepts clés du cours",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 14,
                'title_en' => 'Next steps',
                'title_fr' => "Prochaines étapes",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 15,
                'title_en' => 'Identify when to use each Power Platform component application to create business solutions',
                'title_fr' => "Identifiez quand utiliser chaque application de composant Power Platform pour créer des solutions métiers",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 15,
                'title_en' => 'Learn the value of using Power Platform to create business solutions',
                'title_fr' => "Découvrez l’intérêt de l’utilisation de Power Platform pour créer des solutions d’entreprise",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 15,
                'title_en' => 'Learn the components and features of the Power Platform',
                'title_fr' => "Découvrez les composants et les fonctionnalités de Power Platform",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 16,
                'title_en' => 'Describe the difference between Dataverse and Common Data Model',
                'title_fr' => "Décrire la différence entre Dataverse et Common Data Model",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 16,
                'title_en' => 'Explain use cases and limitations of business rules and process flows',
                'title_fr' => "Expliquer les cas d'utilisation et les limites des règles métier et des flux de processus",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 16,
                'title_en' => 'Explain what environments, tables, columns, and relationships are in Dataverse',
                'title_fr' => "Expliquer quels sont les environnements, les tables, les colonnes et les relations dans Dataverse",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 17,
                'title_en' => 'Learn how other organizations digitize their processes using Power Apps',
                'title_fr' => "Découvrez comment d'autres organisations numérisent leurs processus à l'aide de Power Apps",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 17,
                'title_en' => 'See Power Apps in action and learn options for making your first app',
                'title_fr' => "Découvrez Power Apps en action et découvrez les options pour créer votre première application",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 17,
                'title_en' => 'Learn about what Power Apps is and its business value',
                'title_fr' => "Découvrez ce qu'est Power Apps et sa valeur commerciale",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 18,
                'title_en' => 'See how Power Automate works and looks from the user’s perspective',
                'title_fr' => "Découvrez comment Power Automate fonctionne et se présente du point de vue de l'utilisateur",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 18,
                'title_en' => 'Build a simple flow',
                'title_fr' => "Créer un flux simple",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 18,
                'title_en' => 'Learn the business value and features of Power Automate',
                'title_fr' => "Découvrez la valeur commerciale et les fonctionnalités de Power Automate",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 19,
                'title_en' => 'See how Power BI works and looks from the user’s perspective',
                'title_fr' => "Découvrez le fonctionnement et l’apparence de Power BI du point de vue de l’utilisateur",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 19,
                'title_en' => 'Learn how to build a simple Power BI dashboard',
                'title_fr' => "Apprenez à créer un tableau de bord Power BI simple",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 19,
                'title_en' => 'Describe the business value and features of Power BI',
                'title_fr' => "Décrire la valeur commerciale et les fonctionnalités de Power BI",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 20,
                'title_en' => 'Describe the business value and features of Power Virtual Agents',
                'title_fr' => "Décrire la valeur commerciale et les fonctionnalités de Power Virtual Agents",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 20,
                'title_en' => 'Build a basic chatbot',
                'title_fr' => "Construire un chatbot de base",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 20,
                'title_en' => 'Learn essential components that makeup Power Virtual Agents and chatbots',
                'title_fr' => "Découvrez les composants essentiels qui composent les Power Virtual Agents et les chatbots",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 34,
                'title_en' => 'Develop and implement a risk-based IT audit strategy ',
                'title_fr' => "Élaborer et mettre en œuvre une stratégie d’audit informatique basée sur les risques",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 34,
                'title_en' => 'Plan specific audits  ',
                'title_fr' => "Planifier des audits spécifiques",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 34,
                'title_en' => 'Plan specific audits  ',
                'title_fr' => "Planifier des audits spécifiques",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 34,
                'title_en' => 'Conduct audits in accordance with IT audit standards ',
                'title_fr' => "Réaliser des audits conformément aux normes d'audit informatique",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 34,
                'title_en' => 'Report audit findings and make recommendations to key stakeholders ',
                'title_fr' => "Rapporter les résultats de l'audit et faire des recommandations aux principales parties prenantes",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 34,
                'title_en' => 'Conduct follow-ups or prepare status reports  ',
                'title_fr' => "Effectuer des suivis ou préparer des rapports de situation",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 35,
                'title_en' => 'Evaluate the effectiveness of the IT governance structure ',
                'title_fr' => "Évaluer l’efficacité de la structure de gouvernance informatique",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 35,
                'title_en' => 'Evaluate IT organizational structure and human resources (personnel) management  ',
                'title_fr' => "Évaluer la structure organisationnelle informatique et la gestion des ressources humaines (personnel)",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 35,
                'title_en' => 'Evaluate the organization’s IT policies, standards, and procedures',
                'title_fr' => "Évaluer les politiques, normes et procédures informatiques de l’organisation",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 35,
                'title_en' => 'Evaluate the adequacy of the quality management system',
                'title_fr' => "Évaluer l’adéquation du système de management de la qualité",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 35,
                'title_en' => 'Evaluate IT management and monitoring of controls',
                'title_fr' => "Évaluer la gestion informatique et le suivi des contrôles",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 35,
                'title_en' => 'Evaluate IT contracting strategies and policies, and contract management practices',
                'title_fr' => "Évaluer les stratégies et politiques de passation de contrats informatiques, ainsi que les pratiques de gestion des contrats.",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 35,
                'title_en' => 'Evaluate risk management practices ',
                'title_fr' => "Évaluer les pratiques de gestion des risques",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 35,
                'title_en' => 'Evaluate the organization’s business continuity plan ',
                'title_fr' => "Évaluer le plan de continuité des activités de l’organisation",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 36,
                'title_en' => 'Evaluate the business case for proposed investments in information ',
                'title_fr' => "Évaluer l’analyse de rentabilisation des investissements proposés dans l’information",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 36,
                'title_en' => 'Evaluate the project management practices and controls',
                'title_fr' => "Évaluer les pratiques et les contrôles de gestion de projet",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 36,
                'title_en' => 'Conduct reviews to determine whether a project is progressing in accordance with project plans',
                'title_fr' => "Effectuer des examens pour déterminer si un projet progresse conformément aux plans du projet",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 36,
                'title_en' => 'Evaluate controls for information systems',
                'title_fr' => "Évaluer les contrôles des systèmes d’information",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 36,
                'title_en' => 'Evaluate the readiness of information systems for implementation and migration into production ',
                'title_fr' => "Évaluer l'état de préparation des systèmes d'information pour la mise en œuvre et la migration en production",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 36,
                'title_en' => 'Conduct post-implementation reviews of systems',
                'title_fr' => "Évaluer l'état de préparation des systèmes d'information pour la mise en œuvre et la migration en production",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 37,
                'title_en' => 'Conduct periodic reviews of information systems ',
                'title_fr' => "Effectuer des revues périodiques des systèmes d'information",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 37,
                'title_en' => 'Evaluate service-level management practices ',
                'title_fr' => "Évaluer les pratiques de gestion des niveaux de service",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 37,
                'title_en' => 'Evaluate third-party management practices ',
                'title_fr' => "Évaluer les pratiques de gestion des tiers",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 37,
                'title_en' => 'Evaluate data administration practices',
                'title_fr' => "Évaluer les pratiques d’administration des données",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 37,
                'title_en' => 'Evaluate the use of capacity and performance monitoring tools and techniques ',
                'title_fr' => "Évaluer l’utilisation des outils et techniques de suivi des capacités et des performances",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 37,
                'title_en' => 'Evaluate change, configuration, and release management practices ',
                'title_fr' => "Évaluer les pratiques de gestion des changements, de la configuration et des versions",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 38,
                'title_en' => 'Evaluate the information security policies, standards, and procedures',
                'title_fr' => "Évaluer les politiques, normes et procédures de sécurité de l’information",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 38,
                'title_en' => 'Evaluate the design, implementation, and monitoring of system and logical security',
                'title_fr' => "Évaluer la conception, la mise en œuvre et la surveillance de la sécurité du système et de la logique",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 38,
                'title_en' => 'Evaluate the design, implementation, and monitoring of physical access and environmental controls ',
                'title_fr' => "Évaluer la conception, la mise en œuvre et la surveillance des contrôles d’accès physique et environnementaux",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 38,
                'title_en' => 'Evaluate the processes and procedures used to store, retrieve, transport, and dispose of information assets  ',
                'title_fr' => "Évaluer les processus et procédures utilisés pour stocker, récupérer, transporter et éliminer les actifs informationnels",
                'created_at' => now(),
                'updated_at' => now(),
            ],











        ]);
    }
}
